#! /bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh

bspc monitor DisplayPort-1 -s HDMI-A-0

xrandr --output DisplayPort-1  --gamma 1:1:0.98
xrandr --output HDMI-A-0  --gamma 0.85:0.93:1

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor ^1 -d I II III IV V
bspc monitor ^2 -d VI VII VIII IX

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a discord desktop='^6'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
